// <auto-generated />
namespace eLibrary.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201503291510497_mdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
